plugin.entrypoint=com.infinitestack.recomendador.Application
plugin.base-path=/api/plugins/recomendador-manejo
plugin.requires-host-bridge=true
plugin.requires-host-authentication=true
plugin.requires-host-authorization=true
plugin.requires-host-datasource=true
