plugin.entrypoint=com.infinitestack.satellitehubviewer.Application
plugin.base-path=/api/plugins/satellite-hub-viewer
plugin.requires-host-bridge=true
plugin.requires-host-authentication=true
plugin.requires-host-authorization=true
plugin.requires-host-datasource=true
